---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
#    - name: Start Docker Service
#      service:
#        name: docker
#        state: started

    - name: Pull Image
      shell: docker pull pranav243/calculator:latest

    - name: Run the container
      shell: docker create -it --name Calculator pranav243/calculator